language: php
dist: xenial
cache:
  directories:
    - $HOME/.composer/cache
php:
  - 5.6
  - 7.0
env:
  global:
    - APP_ENV='testing'
sudo: false
before_install:
  - echo $REPO
  - rm -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
  - composer self-update
install: travis_retry composer install --prefer-source --no-interaction
script: vendor/bin/phpunit --verbose
