os: linux
dist: focal
language: php
cache:
  directories:
    - $HOME/.composer/cache
php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4
env:
  global:
    - APP_ENV='testing'
  jobs:
    - PREFER_LOWEST='--prefer-lowest'
    - PREFER_LOWEST=''
before_install:
  - echo $REPO
  - rm -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
  - composer self-update
install: travis_retry composer install --no-interaction $PREFER_LOWEST
script: vendor/bin/phpunit --verbose
